example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from . import views

app_name = 'katalog'

urlpatterns = [
    path('', views.index, name="index")
]

mywatchlist/urls.py
from django.urls import path
from . import views

app_name = 'mywatchlist'

urlpatterns = [
    path('', views.index, name="index"),
    path('html/', views.show_html, name="show_html"),
    path('json/', views.show_json, name="show_json"),
    path('xml/', views.show_xml, name="show_xml")
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from . import views

app_name = "todolist"

urlpatterns = [
    path('', views.show_todolist, name="show_todolist"),
    path('login/', views.login_user, name="login"),
    path('register/', views.register, name="register"),
    path('create-task/', views.create_task, name="create_task"),
    path('logout/', views.logout_user, name="logout"),
    path('delete_task/<int:task_id>', views.delete_task, name="delete_task"),
    path('selesaikan_task/<int:task_id>', views.selesaikan_task, name="selesaikan_task"),
    path('json', views.show_todolist_json, name="json_todolist"),
    path('add', views.add_task_ajax, name="add_task_ajax"),
    path('delete/<int:id>', views.delete_task_ajax, name="delete_task_ajax"),
    path('finish_task/<int:id>', views.finish_task_ajax, name="finish_task_ajax"),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    rating = models.FloatField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from datetime import datetime
import django
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=django.utils.timezone.now)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
# TODO: Create your views here.
from .models import CatalogItem
def index(request):
    catalog_items = CatalogItem.objects.all()
    context = {
        'name': 'Alek Yoanda Partogi.T',
        'id': '2106750276',
        'catalogs': catalog_items
    }
    return render(request, 'katalog.html', context)

mywatchlist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import MyWatchList
from django.core import serializers

def index(request):
    return render(request, 'mywatchlist/index.html')

def show_html(request):
    watchlists = MyWatchList.objects.all()
    watched = MyWatchList.objects.filter(watched=True)
    context = {
        'name': 'Alek Yoanda Partogi.T',
        'id': '2106750276',
        'watchlists': watchlists,
        'amount_watched': len(watched),
        'amount_unwatched': len(watchlists) - len(watched)
    }
    return render(request, 'mywatchlist/mywatchlist.html', context)

def show_json(request):
    watchlists = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", watchlists), content_type="application/json")

def show_xml(request):
    watchlists = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", watchlists), content_type="application/xml")

todolist/views.py
import json
from django.shortcuts import render, redirect
from urllib3 import Retry
from todolist.models import Task
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
@login_required(login_url='/todolist/login')
def show_todolist(request):
    user = request.user
    tasks = Task.objects.filter(user=user)
    if len(tasks) == 0:
        tasks = None
    context = {
        "nama": user.username,
        "tasks": tasks
    }
    return render(request, "todolist_ajax.html", context)

def show_todolist_json(request):
    if request.method == "GET":
        data = Task.objects.filter(user=request.user)
        return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    
def add_task_ajax(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        new_task = Task.objects.create(user=request.user, title=title, description=description)
        
        serialize_json = serializers.serialize('json', [new_task])
        print(serialize_json)
        
        return HttpResponse(serialize_json)

    return JsonResponse({"error": "Not an ajax request"}, status=400)

def delete_task_ajax(request, id):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == "DELETE":
        task = Task.objects.get(pk=id)
        task.delete()
        return HttpResponse("Success Deleting Task")
    return JsonResponse({"error": "Not an ajax request"}, status=400)

def finish_task_ajax(request, id):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == "POST":
        task = Task.objects.get(pk=id)
        task.is_finished = True
        task.save()
        return HttpResponse("Success updating task")
    return JsonResponse({"error": "Not an ajax request"}, status=400)

def create_task(request):
    if (request.method == "POST"):
        title = request.POST["title"]
        description = request.POST["description"]
        
        new_task = Task.objects.create(user=request.user, title=title, description=description)
        return redirect('todolist:show_todolist')

    return render(request, "create_task.html")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    if request.user.is_authenticated:
        return redirect(reverse('todolist:show_todolist')) 
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login') # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    if request.user.is_authenticated:
        return redirect(reverse('todolist:show_todolist')) 
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def delete_task(request, task_id):
    task_to_delete = Task.objects.get(pk=task_id)
    task_to_delete.delete()
    return redirect('todolist:show_todolist')
    
def selesaikan_task(request, task_id):
    task_to_update = Task.objects.get(pk=task_id)
    task_to_update.is_finished = True
    task_to_update.save()
    return redirect('todolist:show_todolist')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{ name }}</p>

  <h5>Student ID: </h5>
  <p>{{ id }}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% for catalog in catalogs %}
    <tr>
      <th>{{ catalog.item_name }}</th>
      <th>{{ catalog.item_price }}</th>
      <th>{{ catalog.item_stock }}</th>
      <th>{{ catalog.description }}</th>
      <th>{{ catalog.rating }}</th>
      <th><a href={{ catalog.item_url }}>{{ catalog.item_url }}</a></th>
    </tr>
    {% endfor %}
    {% comment %} Add the data below this line {% endcomment %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{ name }}</p>

  <h5>Student ID: </h5>
  <p>{{ id }}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% for watchlist in watchlists %}
    <tr>
      <th>{% if watchlist.watched %}
        Yes
        {% else %}
        Not yet
        {% endif %}</th>
      <th>{{ watchlist.title }}</th>
      <th>{{ watchlist.rating }}</th>
      <th>{{ watchlist.release_date }}</th>
      <th>{{ watchlist.review }}</th>
    </tr>
    {% endfor %}
    {% comment %} Add the data below this line {% endcomment %}
  </table>
  <h2>
    {% if amount_unwatched < amount_watched %}
        Selamat, kamu sudah banyak menonton!
    {% else %}
        Wah, kamu masih sedikit menonton!
    {% endif %}
  </h2>

 {% endblock content %}

mywatchlist/templates/mywatchlist/index.html
{% extends 'base.html' %}

 {% block content %}
    <ul>
        <li><a href="{% url 'mywatchlist:show_html' %}">Show html</a></li>
        <li><a href="{% url 'mywatchlist:show_json' %}">Show json</a></li>
        <li><a href="{% url 'mywatchlist:show_xml' %}">Show xml</a></li>
    </ul>
    

 {% endblock content %}

mywatchlist/templates/mywatchlist/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{ name }}</p>

  <h5>Student ID: </h5>
  <p>{{ id }}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% for watchlist in watchlists %}
    <tr>
      <th>{% if watchlist.watched %}
        Yes
        {% else %}
        Not yet
        {% endif %}
      </th>
      <th>{{ watchlist.title }}</th>
      <th>{% if watchlist.rating >= 0 %}
        {{ watchlist.rating }}
        {% else %}
        -
        {% endif %}
      </th>
      <th>{{ watchlist.release_date }}</th>
      <th>{{ watchlist.review }}</th>
    </tr>
    {% endfor %}
    {% comment %} Add the data below this line {% endcomment %}
  </table>
  <h2>
    {% if amount_unwatched <= amount_watched %}
        Selamat, kamu sudah banyak menonton!
    {% else %}
        Wah, kamu masih sedikit menonton!
    {% endif %}
  </h2>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

todolist/templates/backup_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Todolist</title>
<link rel="stylesheet" href="{% static 'todolist/style_index.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-light px-5 mb-3" id="navbar-todolist">
    <span class="navbar-brand mb-0 h1">{{ nama }}</span>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Create Task
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Add task</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-login">
                    <div class="login-form">
                        <form method="POST" action="" id="add-task-form">
                            {% csrf_token %}
                            <table>
                                <tr>
                                    <td>Title: </td>
                                    <td><input type="text" name="title" placeholder="Title" class="form-control" id="title-input"></td>
                                </tr>
                                        
                                <tr>
                                    <td>Description: </td>
                                    <td><textarea name="description" placeholder="Description" class="form-control" cols="30" rows="4"></textarea></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="add-task-ajax">Add Task</button>
            </div>
        </div>
    </div>
</div>
    <a href="{% url 'todolist:logout' %}">Logout</a>
</nav>


<div class="container">
    <br>
    <div class="row" id="card-grid">
        {% if tasks %}
            <h1 class="text-center" id="task-exist-h1">Todolist</h1>
            {% for task in tasks %}
                <div class="col-lg-4 col-md-6 col-sm-10 col-xs-1 mb-4" id="task-card-{{task.id}}">
                    <div class="card border-light mx-auto" id="card" style="width: 22rem;">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h5 class="card-title">{{ task.title }}</h5>
                                <div class="d-flex justify-content-end">
                                    {% if not task.is_finished %}
                                        <div id="finish-task-ajax"> 
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-check-circle text-muted" id="check_task" viewBox="0 0 16 16">
                                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                                <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                                            </svg>
                                        </div>
                                    {% endif %}
                                    <div class="delete-task-ajax" id="{{ task.pk }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash text-muted" id="delete_task" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                            {% if task.is_finished %}
                            <h6 class="card-subtitle mb-2 text-success" style="color:green;">Selesai</h6>
                            {% else %}
                            <h6 class="card-subtitle mb-2 text-danger" style="color:red;">Belum Selesai</h6>
                            {% endif %}
                            
                            <p class="card-text">{{ task.description }}</p>
                            <p class="card-text text-muted">{{ task.date }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="d-flex justify-content-center" id="no-task-div">
                <h1>No Task :)</h1>
            </div>
        {% endif %}
        
    </div>

<script src="{% static 'todolist/js/script.js' %}" type="text/javascript"></script>  
{% endblock content %}

todolist/templates/create_task.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Create Task</title>
<link rel="stylesheet" href="{% static 'todolist/style_login.css' %}">
{% endblock meta %}

{% block content %}

<div class="container-login">
    <div class="login-form">
        <h2>Create Task</h2>
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Title: </td>
                    <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Description: </td>
                    <td><textarea name="description" placeholder="Description" class="form-control" cols="30" rows="4"></textarea></td>
                </tr>
    
                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Create"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
    
    </div>
</div>


{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'todolist/style_login.css' %}">
{% endblock meta %}

{% block content %}

<div class="container-login">
    <div class = "login-form">

        <h2>Login</h2>
    
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr id="submit-container">
                    <td id="input-submit"><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        <h5>Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></h5>
    
    </div>
</div>


{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Registrasi Akun</title>
<link rel="stylesheet" href="{% static 'todolist/style_login.css' %}">
{% endblock meta %}

{% block content %}  
<div class="container-login">
    <div class = "register-form">
        <h2>Formulir Registrasi</h2>  
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>
    
        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    
    </div>  
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Todolist</title>
<link rel="stylesheet" href="{% static 'todolist/style_index.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-light px-5 mb-3" id="navbar-todolist">
    <span class="navbar-brand mb-0 h1">{{ nama }}</span>
    <button class="btn btn-light" id="btn-main"><a href="{% url 'todolist:create_task' %}">Create Task</a></button>
    <a href="{% url 'todolist:logout' %}">Logout</a>
  </nav>


{% if tasks %}
    <div class="container">
        <h1 class="text-center">Todolist</h1>
        <br>
        <div class="row" id="card-grid">
            {% for task in tasks %}
            <div class="col-lg-4 col-md-6 col-sm-10 col-xs-1 mb-4" >
                <div class="card border-light mx-auto" id="card" style="width: 22rem;">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <h5 class="card-title">{{ task.title }}</h5>
                            <div class="d-flex justify-content-end">
                                {% if not task.is_finished %}
                                    <a href="{% url 'todolist:selesaikan_task' task.id %}">    
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-check-circle text-muted" id="check_task" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                        <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                                    </svg>
                                    </a>
                                {% endif %}
                                <a href="{% url 'todolist:delete_task' task.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash text-muted" id="delete_task" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg>
                                </a>
                            
                            </div>
                        </div>
                        {% if task.is_finished %}
                        <h6 class="card-subtitle mb-2 text-success" style="color:green;">Selesai</h6>
                        {% else %}
                        <h6 class="card-subtitle mb-2 text-danger" style="color:red;">Belum Selesai</h6>
                        {% endif %}
                        
                        <p class="card-text">{{ task.description }}</p>
                        <p class="card-text text-muted">{{ task.date }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    
{% else %}
<div class="d-flex justify-content-center">
    <h1>No Task :)</h1>
</div>

{% endif %}




{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Todolist</title>
<link rel="stylesheet" href="{% static 'todolist/style_index.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-light px-5 mb-3" id="navbar-todolist">
    <span class="navbar-brand mb-0 h1">{{ nama }}</span>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Create Task
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Add task</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-login">
                    <div class="login-form">
                        <form method="POST" action="" id="add-task-form">
                            {% csrf_token %}
                            <table>
                                <tr>
                                    <td>Title: </td>
                                    <td><input type="text" name="title" placeholder="Title" class="form-control" id="title-input"></td>
                                </tr>
                                        
                                <tr>
                                    <td>Description: </td>
                                    <td><textarea name="description" placeholder="Description" class="form-control" cols="30" rows="4"></textarea></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="add-task-ajax">Add Task</button>
            </div>
        </div>
    </div>
</div>
    <a href="{% url 'todolist:logout' %}">Logout</a>
</nav>


<div class="container">
    <br>
    <div class="row" id="card-grid"></div>
</div>

<script src="{% static 'todolist/js/script.js' %}" type="text/javascript"></script>  
{% endblock content %}